---
- hosts: all
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
